live_config_reload = true

import = [
    "~/.config/alacritty/colors/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
blur = true
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 10.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "FiraMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Medium"
