[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.normal]
black = "#26233a"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.bright]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ebbcba"
green = "#31748f"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"
